baseURL = "https://hotdogsandeggs.com/"
languageCode = "en-us"
title = "Chris Gallo | Home"

[params]
    author = "Chris Gallo"
    description = "This is the website of Chris Gallo. It's a place for him to stay curious."	
