baseURL = "https://hotdogsandeggs.com/"
languageCode = "en-us"
title = "Chris Gallo | Home"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[params]
    author = "Chris Gallo"
    description = "Chris Gallo lives in Charlotte, NC and this website is a place for me to stay curious."

