baseURL = "https://hotdogsandeggs.com/"
languageCode = "en-us"
title = "Chris Gallo | Home"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[params]
    author = "Chris Gallo"
    description = "Chris Gallo lives in Charlotte and works at Highrise, where he makes customers feel important."

