# ==========================
# == Jekyll Configuration ==
# ==========================
permalink: pretty
safe: false

# ==========================
# == Custom Configuration ==
# ==========================

title: Chris Gallo | Hot Dogs and Eggs
subtitle: "The website of Chris Gallo."
url: http://hotdogsandeggs.com
description: "Chris Gallo spends his days making customers feel important at Highrise."
navigation:
 - title: Blog
   url: http://blog.hotdogsandeggs.com
 - title: People
   url: http://people.hotdogsandeggs.com
 - title: Say hi
   url: mailto:chris@hotsdogsandeggs.com


gems:
 - jekyll-redirect-from



