# ==========================
# == Jekyll Configuration ==
# ==========================
permalink: pretty
safe: false

# ==========================
# == Custom Configuration ==
# ==========================

title: Chris Gallo | Hot Dogs and Eggs
subtitle: "The website of Chris Gallo."
url: http://hotdogsandeggs.com
description: "Chris Gallo lives in Charlotte and works at Highrise, where he makes customers feel important."
navigation:
 - title: Blog
   url: http://blog.hotdogsandeggs.com
 - title: People
   url: http://people.hotdogsandeggs.com


gems:
 - jekyll-redirect-from



