# ==========================
# == Jekyll Configuration ==
# ==========================
permalink: pretty
safe: false

# ==========================
# == Custom Configuration ==
# ==========================

title: Chris Gallo | Hot Dogs and Eggs
subtitle: "The online home of Chris Gallo."
url: https://hotdogsandeggs.com/
description: "Chris Gallo lives in Charlotte and works at Highrise, where he makes customers feel important."
navigation:
 - title: Blog
   url: https://blog.hotdogsandeggs.com
 - title: People
   url: https://people.hotdogsandeggs.com


gems:
 - jekyll-redirect-from



