# ==========================
# == Jekyll Configuration ==
# ==========================
permalink: pretty
safe: false

# ==========================
# == Custom Configuration ==
# ==========================

title: Chris Gallo | Hot Dogs and Eggs
subtitle: "The online home of Chris Gallo."
url: https://hotdogsandeggs.com/
description: "Chris Gallo lives in Charlotte and works at Highrise, where he makes customers feel important."
navigation:
 - title: Blog
   url: https://blog.hotdogsandeggs.com
 - title: People
   url: https://people.hotdogsandeggs.com

# ==========================
# == Collections ==
# ==========================

collections:
  R:
    title: R Programming
    description: Open source langauge for statistics and graphics. Data scientists use it. These notes are from the lessons in the <a href="http://swirlstats.com/students.html" >swirl package</a> in R Studio.
    output: true
    permalink: /r/:title


gems:
 - jekyll-redirect-from



